### DISCUSSION TITLE
Hardware encoding in plex?

### DISCUSSION THREAD

**Discussion by LarsNorgaard** [runtipi/runtipi-appstore#3082] [Q&A]
Hi,

I tried looking at the docker-compose.yaml for Plex, but I don't see device pass through. 

Or do all apps run with elevated access to hardware?

**Comment by JigSawFr** [comment]
Totally,
you can add it by adding a custom user-config plex compose file with:

```
services:
  plex:
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c *:* rmw'
```
