### DISCUSSION TITLE
wg-easy broke

### DISCUSSION THREAD

**Discussion by sayedhfatimi** [runtipi/runtipi-appstore#4702] [Q&A] [answered]
wg-easy recently broke due to an update in the image requiring `PASSWORD_HASH` environment variable rather than `PASSWORD` (bought my entire network down *sigh*) the image wont start up at all unless this variable is updated or omitted entirely. thought id share my temporary fix and hopefully get ideas from others for better workarounds

temporary fix:

> fork the runtipi-appstore repo and add your fork to `Apps repo URL` in settings

1. update `config.json` to remove the password field.
2. update `docker-compose.yml` to remove the `PASSWORD` environment variable

>  if you dont intend to expose the web interface on the internet, you can stop here

3. add `docker-compose.yml` to `~/runtipi/user-config/wg-easy`
4. add `PASSWORD_HASH` environment variable, generate your hash using: [bcrypt generator](https://bcrypt-generator.com/), use 12 rounds of salt as this is the requirement in [wg-easy generateHash fn](https://github.com/wg-easy/wg-easy/blob/master/src/wgpw.mjs), add an additional `$` before each existing `$` symbol

> ~/runtipi/user-config/wg-easy/docker-compose.yml
```yaml
services:
  wg-easy:
    environment:
      PASSWORD_HASH: <YOUR_HASH> // e.g. $$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
```
6. login via web interface using your password
7. profit!
