### DISCUSSION TITLE
How to workaround "mutually exclusive 'network_mode' and 'networks'"?

### DISCUSSION THREAD

**Discussion by Lockszmith-GH** [runtipi/runtipi-appstore#5540] [Q&A] [answered]
When I run docker-compose based services that need 'full reign' of a host's port range, I prefer using `ipvlan` over `network_mode: host`.
On my runtipi machine, I've tried and tested a manual docker-compose file and it worked perfectly.

I tried doing that with the runtipi `plex` and user-config mod and got the following error:

```log
worker: 2024-11-14T20:00:35.431Z - info >       Starting app plex
worker: 2024-11-14T20:00:35.457Z - info >       Regenerating app.env file for app plex
worker: 2024-11-14T20:00:35.470Z - info >       Running docker compose with args --env-file /app-data/plex/app.env --env-file /data/user-config/plex/app.env --project-name plex -f /data/apps/plex/docker-compose.yml -f /data/repos/29ca930bfdaffa1dfabf5726336380ede7066bc53297e3c0c868b27c97282903/apps/docker-compose.common.yml --file /data/user-config/plex/docker-compose.yml up --detach --force-recreate --remove-orphans --pull always
worker: 2024-11-14T20:00:35.684Z - error >      An error occurred: Error with your custom app: Command failed: docker-compose --env-file /app-data/plex/app.env --env-file /data/user-config/plex/app.env --project-name plex -f /data/apps/plex/docker-compose.yml -f /data/repos/29ca930bfdaffa1dfabf5726336380ede7066bc53297e3c0c868b27c97282903/apps/docker-compose.common.yml --file /data/user-config/plex/docker-compose.yml up --detach --force-recreate --remove-orphans --pull always
time="2024-11-14T20:00:35Z" level=warning msg="/data/apps/plex/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
time="2024-11-14T20:00:35Z" level=warning msg="/data/repos/29ca930bfdaffa1dfabf5726336380ede7066bc53297e3c0c868b27c97282903/apps/docker-compose.common.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
service plex declares mutually exclusive `network_mode` and `networks`: invalid compose project
. Before opening an issue try to remove any user-config files or any custom app-store repo and try again.
worker: 2024-11-14T20:00:35.685Z - error >      Error starting app plex
```

<details> <summary>My <code>user-config/plex/docker-compose.yml</code> - click to expand</summary>

```yaml
services:
  plex:
    networks:
      lan:
        ipv4_address: 192.168.<redacted>
    environment:
      PUID: "${MY_USER_UID}"
      PGID: "${MY_USER_GID}"
   <volumes definition>

networks:
  lan:
    driver: ipvlan
    ipam:
      config:
        - subnet: ${MY_SUBNET}
          gateway: ${MY_IPv4_GW}
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      parent: ${MY_NET_IF}
```

</details>

## My question
Is there a way to override the `network_mode: host` entry and specify `networks` in the custom compose yaml file?

**Comment by Lockszmith-GH** [comment, marked as answer]
Update: I believe I managed to answer myself eventually.

## A detour - somewhat educational
I found a relevant question in SO (even before I asked the question here), but for some reason the answers didn't work for me at first.
Then I went on a wild goose-chase after reading <b>@</b>**meienberger**'s suggestion [here](https://github.com/runtipi/runtipi/issues/222). (I've added it as a reply under this thread, as I still learned some stuff there, so it might be of interest.

I circled back to the SO question, [specifically this comment](https://stackoverflow.com/questions/69584848/how-to-unset-network-mode-in-an-overriding-docker-compose-file#comment127242966_71230720), and indeed adding `network_host: ""` allowed me to spin `plex` up and have it attached to the relevant network I've setup using `sleeping-beauty` AND assign the static IP I wanted.

<details> <summary>My <code>sleeping-beauty</code> based <code>compose.yml</code> - click to expand</summary>

```yaml
services:
  plex-network:
    image: tianon/sleeping-beauty
    container_name: plexnet
    networks:
      lan:
        ipv4_address: 192.168.<redacted> # (different than the one assigned to Plex)
    restart: unless-stopped

networks:
  lan:
    driver: ipvlan
    ipam:
      config:
        - subnet: ${MY_SUBNET}
          gateway: ${MY_IPv4_GW}
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      parent: ${MY_NET_IF}
```

</details>

<details> <summary>My <code>user-config/plex/docker-compose.yml</code> - click to expand</summary>

```yaml
services:
  plex:
    network_mode: ""
    networks:
      lan:
        ipv4_address: 192.168.<redacted> # (different than the one assigned to Plex)
    environment:
      PUID: "${MY_USER_UID}"
      PGID: "${MY_USER_GID}"
   <volumes definition>

networks:
  lan:
    external: true
```

</details>

**Reply by Lockszmith-GH** [reply]
### The pre-update post, aka the detour:
Below is what I thought would be the solution, but failed me upon testing. Still might be of interest.
___

I couldn't figure out what would be the docker compose overriding of network_mode is, maybe this should be handled by runtipi's template engine?

For the time-being, I'm going to spin up a dummy `plexnet` service with the `tianon/sleeping-beauty` and then use `network_mode: container:plexnet` similar to <b>@</b>**meienberger**'s suggesting [here](https://github.com/runtipi/runtipi/issues/222) - this at least overwrites the existing `network_mode`.

(I think this is what I like most about runtipi, the fact that after all, it's plain docker-compose and there is usually a solution in that realm that will still allow us to use the awesome runtipi infrastructure with our modifications)

<details> <summary>My <code>sleeping-beauty</code> based <code>compose.yml</code> - click to expand</summary>

```yaml
services:
  plex-network:
    image: tianon/sleeping-beauty
    container_name: plexnet
    networks:
      lan:
        ipv4_address: 192.168.<redacted>
    restart: unless-stopped

networks:
  lan:
    driver: ipvlan
    ipam:
      config:
        - subnet: ${MY_SUBNET}
          gateway: ${MY_IPv4_GW}
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      parent: ${MY_NET_IF}
```

</details>

<details> <summary>My <code>user-config/plex/docker-compose.yml</code> - click to expand</summary>

```yaml
services:
  plex:
    network_mode: container:plexnet
    environment:
      PUID: "${MY_USER_UID}"
      PGID: "${MY_USER_GID}"
   <volumes definition>
```

</details>
