### DISCUSSION TITLE
add option to add dns server to the dynamic compose

### DISCUSSION THREAD

**Discussion by falkheiland** [runtipi/runtipi-appstore#7717] [Ideas]
https://github.com/runtipi/runtipi-appstore/blob/715b18ad5c9305834ae63bc22b594a87c80c42ac/apps/dynamic-compose-schema.json

```yml
services:
  service1:
    dns:
      - 1.1.1.1
      - 1.0.0.1
```
