### ISSUE TITLE
🐛 [Kasm Workspaces] Incorrect Port Config and not Properly Start 

### ISSUE THREAD

**Issue by CaenJones** [runtipi/runtipi-appstore#1766]
Hello, I just recently tried to install kasm workplaces from the runtipi appstore. After the initial install and forwarding the port shown on the readme, I tried to access the forwarded page only to get a `bad gateway` error. 

![Screenshot_20231206_212554](https://github.com/runtipi/runtipi-appstore/assets/131218155/c5a1ce98-be20-42b5-8c5e-dfb25b1291cd)

I then consulted the original documentation for the ported container.  The docker compose file for kasm needs to include something like this:

```
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
```
and for the port setup: 
```
  ports:
      - 3000:3000
      - 443:443
```

However after making changes similar to the ones shown above I still receive the same error. The operating system I use as  a base is Ubuntu 22.04 LTS. 

Thank you for your help!
