### ISSUE TITLE
[APP REQUEST] WOODPECKER CI CD

### ISSUE THREAD

**Issue by bugsbunny88** [runtipi/runtipi-appstore#1995]
Have you considered adding the app yourself? 
- don't know how to integrate it well, I know how to do it in isolation on a LXC with the compose example provided.

**Describe app**

- get started with CI CD with the already provided Forgejo/Gitea instances
- light weight CI CD , beginner friendly
- don't see anything comparable already in the available apps

**Links**
- Official repository: [https://github.com/woodpecker-ci/woodpecker]
- Official docker image: [https://hub.docker.com/u/woodpeckerci] (consists of server + client)
- Docs: https://woodpecker-ci.org/

Include links to alln other the available resources for the app. (eg: website, license)

**Additional context**

compose example that works on its own LXC for me:
```
---
version: "3.8"
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    networks:
      - woodpecker
      - proxy
    environment:
      - "WOODPECKER_OPEN=true"
      - "WOODPECKER_HOST=${WOODPECKER_URL}"
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
      - "WOODPECKER_ADMIN=${WOODPECKER_ADMIN}"
      - "WOODPECKER_GITEA=true"
      - "WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}"
      - "WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}"
      - "WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}"
      - "WOODPECKER_GITEA_SKIP_VERIFY=true"
    volumes:
      - "./data:/var/lib/woodpecker"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.woodpecker.rule=Host(`${WOODPECKER_HOST}`)"
      - "traefik.http.routers.woodpecker.tls=true"
      - "traefik.http.routers.woodpecker.entrypoints=https"
      - "traefik.http.services.woodpecker.loadbalancer.server.port=8000"
  woodpecker-agent:
    container_name: woodpecker-agent
    image: woodpeckerci/woodpecker-agent:latest
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - woodpecker-server
    networks:
      - woodpecker
    environment:
      - "WOODPECKER_SERVER=woodpecker-server:9000"
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  woodpecker:
  proxy:
    external: true
```

**Checklist**
- [X] I have put the app name in the title of the issue
- [X] I have linked the repository of the app
- [X] I have linked the official docker image
