### ISSUE TITLE
🐛 [2FAuth] app does not work anymore

### ISSUE THREAD

**Issue by falkheiland** [runtipi/runtipi-appstore#2243]
app does not work anymore. there is an open issue at the maintainer

https://github.com/Bubka/2FAuth/issues/284

_Originally posted by @falkheiland in https://github.com/runtipi/runtipi-appstore/issues/2178#issuecomment-1902229917_

**Comment by falkheiland** [comment]
by using runtipi/user-config/2fauth/docker-compose.yml

```
version: "3.7"
services:
  2fauth:
    environment:
      - ASSET_URL=https://2fauth.${LOCAL_DOMAIN}
      - APP_URL=https://2fauth.${LOCAL_DOMAIN}
```

i got it working again. the original app package does not specify those env, but they seem to be needed / defined to work with 5.0.3.

**Comment by JigSawFr** [comment]
Thanks @falkheiland

**Comment by JigSawFr** [comment]
Hum, 1st try, failing. Troubleshooting

```Running version 5.0.3 commit 35f2f1d built on 2024-01-19T14:54:35Z
supervisord version: v0.6.8
PHP 8.1.22 (fpm-fcgi) (built: Aug  3 2023 23:11:21)
nginx version: nginx/1.22.1
touch: /2fauth/database.sqlite: Permission denied````

**Comment by falkheiland** [comment]
#2254 introduced
 
 ```
      - ASSET_URL=https://${APP_DOMAIN}
      - APP_URL=https://${APP_DOMAIN}
```

since 2FAuth only listens on the APP_URL , using APP_DOMAIN only works if the app is published.
using LOCAL_DOMAIN is also only useful if accessed locally.
Maybe ist makes sense to provide additional info in the APP-Test as to how use a user-config to use LOCAL_DOMAIN instead if necessary?

something like that:


-----------------
to use 2FAuth on a local domain create a file:
- runtipi/user-config/2fauth/docker-compose.yml
an specify:

```yml
version: "3.7"
services:
  2fauth:
    environment:
      - ASSET_URL=https://2fauth.${LOCAL_DOMAIN}
      - APP_URL=https://2fauth.${LOCAL_DOMAIN}
```
