### ISSUE TITLE
Pi-Hole: Make DHCP server available

### ISSUE THREAD

**Issue by sgvandijk** [runtipi/runtipi-appstore#44]
Thanks for this project, it seems very promising! I have started using it to replace manual installs of different apps on my Raspberry Pi, and the core app I want to run is Pi-Hole. Unfortunately it is not possible to use it as-is in my situation.

The main problem is that my router does not allow to change the default DNS server(s) provided by its DHCP service. So in my old, manual, installation, I enabled Pi-Hole's option to provide DHCP, and turned it off at the router. As described e.g. [here](https://discourse.pi-hole.net/t/how-do-i-use-pi-holes-built-in-dhcp-server-and-why-would-i-want-to/3026).

Unfortunately when Pi-Hole runs inside Docker, some additional networking setup is required, as is detailed [here in Pi-hole's documentation](https://docs.pi-hole.net/docker/dhcp/).

I am not sure which of those options is best for Tipi. The host networking mode is out immediately I guess due to port conflicts.

The macvlan option then seems the best in the sense that it doesn't require anything external, though it will probably need more configuration settings, such as the interface to use (for me wireless) and the gateway + subnet + ip range to use. Which is probably irrelevant and confusing to many users, and I can understand goes against Tipi's aim 'to remove the need for manual configuration and network setup.' :)

I will see if I can find a better solution still, but thought I would raise this here in case anybody more capable in Docker networking would know something.

**Comment by meienberger** [comment]
@sethforprivacy I think this would makes yes. What ports does Pi-Hole expose besides 53?
@sgvandijk You can still edit the docker-compose.yml file to your needs (located in `runtipi/apps/pihole`)

**Comment by sgvandijk** [comment]
The main conflict would be port 80 for the web interface. I initially thought this would be an issue because standard guides for pi-hole say this needs to be changed in a configuration file, however from [here](https://github.com/pi-hole/docker-pi-hole/issues/404) it turns out that you can use the `WEB_APP` environment variable after all.

I have updated `docker-compose.yml` to the following and can confirm that with that both DNS and DHCP work well, and all works fine from Tipi as well:

```yaml
version: "3.7"

services:
  # unbound:
  #   image: "klutchell/unbound"
  #   container_name: unbound
  #   restart: unless-stopped
  #   volumes:
  #     - "${APP_DATA_DIR}/data/unbound:/etc/unbound"
  #   networks:
  #     tipi_main_network:
  #       ipv4_address: 10.21.21.200

  pihole:
    # depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:2022.07.1
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      # - 10.21.21.200 # Points to unbound
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${APP_PASSWORD}
      # PIHOLE_DNS_: 10.21.21.200 # Points to unbound
      FTLCONF_REPLY_ADDR4: 10.21.21.201
      WEB_PORT: ${APP_PORT}
    cap_add:
      - NET_ADMIN
    network_mode: host
```

If you think that is fine for default behaviour, I will open a PR for that.
