### ISSUE TITLE
🐛 [immich] Connection reset after Update to 1.118

### ISSUE THREAD

**Issue by WoOS2** [runtipi/runtipi-appstore#5226]
### Store Application

immich

### App version

1.118.2

### Description

After updating immich (through runtipi) from 1.117 to 1.118.2, the app still starts but at least local connection (to (localhostname):8128 through the "Open" button on the runtipi app page) leads to a "Connection reset" page ("Fehler: Verbindung unterbrochen" in German).

It appears this error is caused by not adapting the ports in apps/immich/docker-compose.yml according to the release notes of https://github.com/immich-app/immich/releases/tag/v1.118.0 (section "Breaking changes/Port alignment").
At least if I manually change the two 3001 ports in the docker-compose.yml file (in the "ports:" section and in the traeffik-labels section) to 2283 (as mentioned on the above page), immich can be connected to again.

Since I think I am not supposed to manually update apps/immich/docker-compose.yml this is probably a bug.

### Steps to reproduce

1. Have a 1.117 version of immich running
2. Update via runtipi to 1.118.2
3. Connect locally via the "Open" button on the app page of runtipi to immich

P.S.: Doesn't have to be a local connection, a remote connection (i.e. using an own domain) apparently ends up at a 404 page

### App logs

```bash
App logs do not show an error
```

### Browser

Firefox (but irrelevant)

### User-Config changes

I doubt it is relevant but just in case:
--- snip ---
```
services:
  immich:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/volume/Pictures:/cellar
      - /mnt/volume/Pictures:/cellar-ro:ro
      - /mnt/volume/Pictures/immich-uploaded:/usr/src/app/upload/library
  immich-machine-learning:
    volumes:
      - /mnt/volume/Pictures:/cellar
      - /mnt/volume/Pictures:/cellar-ro:ro
      - /mnt/volume/Pictures/immich-uploaded:/usr/src/app/upload/library
  immich-db:
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}
' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; ech
o "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
