### ISSUE TITLE
[Planka] Crash on first run

### ISSUE THREAD

**Issue by TheSonAlsoRises** [runtipi/runtipi-appstore#5401]
### Store Application

Planka

### App version

1.23.4

### Description

Planka fails to initializes on the first run. 

### Steps to reproduce

1. Install Planka from the store
2. Try to launch it

### App logs

```bash
planka-db  |
planka-db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
planka-db  |
planka-db  | 2024-11-02 16:52:49.267 UTC [1] LOG:  starting PostgreSQL 14.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
planka-db  | 2024-11-02 16:52:49.267 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
planka-db  | 2024-11-02 16:52:49.267 UTC [1] LOG:  listening on IPv6 address "::", port 5432
planka-db  | 2024-11-02 16:52:49.280 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
planka-db  | 2024-11-02 16:52:49.285 UTC [25] LOG:  database system was shut down at 2024-11-02 16:52:21 UTC
planka-db  | 2024-11-02 16:52:49.302 UTC [1] LOG:  database system is ready to accept connections
planka     | node:internal/process/promises:288
planka     |             triggerUncaughtException(err, true /* fromPromise */);
planka     |             ^
planka     |
planka     | Error: getaddrinfo EAI_AGAIN base
planka     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
planka     |   errno: -3001,
planka     |   code: 'EAI_AGAIN',
planka     |   syscall: 'getaddrinfo',
planka     |   hostname: 'base'
planka     | }
planka     |
planka     | Node.js v18.20.4
planka     | Tried 1 times. Waiting 5 seconds...
planka     | node:internal/process/promises:288
planka     |             triggerUncaughtException(err, true /* fromPromise */);
planka     |             ^
planka     |
planka     | Error: getaddrinfo EAI_AGAIN base
planka     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
planka     |   errno: -3001,
planka     |   code: 'EAI_AGAIN',
planka     |   syscall: 'getaddrinfo',
planka     |   hostname: 'base'
planka     | }
planka     |
planka     | Node.js v18.20.4
planka     | Tried 2 times. Waiting 5 seconds...
```

### User-Config changes

No changes

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by pmoscode** [comment]
The same behavior here.

**Comment by meienberger** [comment]
I tried all I could to make Planka work but for some reason this error keeps happening. This is the last `docker-compose.yml` I landed with:

```yml
services:
  planka:
    image: ghcr.io/plankanban/planka:1.24.1
    container_name: planka
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/user-avatars:/app/public/user-avatars
      - ${APP_DATA_DIR}/data/project-background-images:/app/public/project-background-images
      - ${APP_DATA_DIR}/data/attachments:/app/private/attachments
    ports:
      - ${APP_PORT}:1337
    environment:
      - BASE_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - DATABASE_URL="postgresql://postgres@planka-db/planka"
      - SECRET_KEY="${PLANKA_SECRET_KEY}"
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.planka-web-redirect.redirectscheme.scheme: https
      traefik.http.services.planka.loadbalancer.server.port: 1337
      # Web
      traefik.http.routers.planka-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.planka-insecure.entrypoints: web
      traefik.http.routers.planka-insecure.service: planka
      traefik.http.routers.planka-insecure.middlewares: planka-web-redirect
      # Websecure
      traefik.http.routers.planka.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.planka.entrypoints: websecure
      traefik.http.routers.planka.service: planka
      traefik.http.routers.planka.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.planka-local-insecure.rule: Host(`planka.${LOCAL_DOMAIN}`)
      traefik.http.routers.planka-local-insecure.entrypoints: web
      traefik.http.routers.planka-local-insecure.service: planka
      traefik.http.routers.planka-local-insecure.middlewares: planka-web-redirect
      # Local domain secure
      traefik.http.routers.planka-local.rule: Host(`planka.${LOCAL_DOMAIN}`)
      traefik.http.routers.planka-local.entrypoints: websecure
      traefik.http.routers.planka-local.service: planka
      traefik.http.routers.planka-local.tls: true
      runtipi.managed: true
    depends_on:
      planka-db:
        condition: service_healthy

  planka-db:
    image: postgres:16-alpine
    container_name: planka-db
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "planka"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
```

I tried to reproduce it from the [official example](https://github.com/plankanban/planka/blob/master/docker-compose.yml) but no luck. If someone could find a solution that would be nice or I will archive this app from the store
